spring:
  datasource:
    url:jdbc:h2:mem: habits-db-local
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
